- Added develop -> main merge restriction

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -14,6 +14,15 @@ permissions:
     pull-requests: write
 
 jobs:
+
+    check_branch:
+        runs-on: ubuntu-latest
+        steps:
+          - name: Check branch
+            if: github.base_ref == 'main' && github.head_ref != 'develop'
+            run: |
+              echo "ERROR: You can only merge to main from develop."
+              exit 1
     
     build:
         strategy:
