Develop (#3)
- Reordered pyproject.toml
- Added coverage options to pyproject.toml
- Added coverage ignore
- fixed publish in github actions
- Added status badges to README
- Added real pypi publishing step to github actions
- Added develop -> main merge restriction
- Updated project version
- Update job names in github actions

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -1,4 +1,4 @@
-name: Python CI
+name: Python CI/CD
 
 on:
     push:
@@ -14,14 +14,22 @@ permissions:
     pull-requests: write
 
 jobs:
+
+    check_branch:
+        runs-on: ubuntu-latest
+        steps:
+          - name: Check branch
+            if: github.base_ref == 'main' && github.head_ref != 'develop'
+            run: |
+              echo "ERROR: You can only merge to main from develop."
+              exit 1
     
     build:
         strategy:
             matrix:
-                os: [ubuntu-latest, macos-latest, windows-latest]
                 python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
 
-        runs-on: ${{matrix.os}}
+        runs-on: ubuntu-latest
 
         steps:
             - name: Build Information
@@ -43,7 +51,7 @@ jobs:
               run: python -m pip install --upgrade pip
 
             - name: Install Package
-              run: pip install -e .[test]
+              run: pip install -e .[ci]
 
             - name: Linting
               run: |
@@ -79,14 +87,75 @@ jobs:
                   status: "${{ job.status }}"
 
     test-pypi-publish:
-        name: publish package to test PyPI
+        if: github.ref == 'refs/heads/develop'
+        name: publish package to PyPI [TEST]
         needs: build
         runs-on: ubuntu-latest
+        environment:
+            name: test
         permissions:
             id-token: write
         
         steps:
+            - name: Build Information
+              run: echo "Publishing package"
+
+            - name: Checkout Code From "${{github.ref_name}}"
+              uses: actions/checkout@v4
+
+            - name: Setup Python
+              uses: actions/setup-python@v4
+              with:
+                  python-version: 3.12
+                  cache: "pip"
+
+            - name: Upgrade Pip
+              run: python -m pip install --upgrade pip
+
+            - name: Install Package
+              run: pip install -e .[ci]
+
+            - name: Build package
+              run: |
+                  python -m build
+
             - name: Publish package distributions to test PyPI
               uses: pypa/gh-action-pypi-publish@release/v1
               with:
                 repository-url: https://test.pypi.org/legacy/
+    
+    pypi-publish:
+        if: github.ref == 'refs/heads/main'
+        name: publish package to PyPI [RELEASE]
+        needs: build
+        runs-on: ubuntu-latest
+        environment:
+            name: release
+        permissions:
+            id-token: write
+        
+        steps:
+            - name: Build Information
+              run: echo "Publishing package"
+
+            - name: Checkout Code From "${{github.ref_name}}"
+              uses: actions/checkout@v4
+
+            - name: Setup Python
+              uses: actions/setup-python@v4
+              with:
+                  python-version: 3.12
+                  cache: "pip"
+
+            - name: Upgrade Pip
+              run: python -m pip install --upgrade pip
+
+            - name: Install Package
+              run: pip install -e .[ci]
+
+            - name: Build package
+              run: |
+                python -m build
+
+            - name: Publish package distributions to PyPI
+              uses: pypa/gh-action-pypi-publish@release/v1
